name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a muti-line script
        run:
          echo What is in this directory?
          ls -a
          echo
          echo Is Java installed?
          java -version
          echo Is Git installed?
          git --version
          echo What about build tools?
          mvn --version
          gradle --version
          ant -version
