name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.5
        with:
          files: |
            *\*

      - name: Run step if any of the listed files above change
        run: |
          for file in ${{ steps.changed-files-specific.outputs. all_changed_files }}; do
            FILEPATH=`$file | awk -F/ '{print FS $1}'`
            echo $file
          done      
