name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      - name: Set up JDK 1.7
        uses: actions/setup-java@v1
        with:
          java-version: 1.7

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.5
        with:
          files: |
            *\*

      - name: Run step if any of the listed files above change
        run: |
          for file in ${{ steps.changed-files-specific.outputs. all_changed_files }}; do
            FILEPATH=$(echo "$file" | cut -d "/" -f1)
            BUIDPATH="${FILEPATH}/pom.xml"
            echo $BUIDPATH
            mvn -B clean package -Pnative --file $BUIDPATH
            mkdir -p staging && cp target/*.jar staging
          done 

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging/
      - name: Clean staging
        run: rm -fr staging     
